name: hphisto
services:
  hphisto:
    cpu_shares: 90
    command: []
    container_name: hphisto
    deploy:
      resources:
        limits:
          memory: 1073741824
        reservations:
          devices: []
    environment:
      - PORT=2346
      - DB_PATH=/data/hphisto.db
      - NODE_ENV=production
      - COOKIE_SECURE=true
      - API_TOKEN=
      - CORS_ORIGIN=*
    image: ghcr.io/clevim/hphisto:latest
    labels:
      icon: https://raw.githubusercontent.com/clevim/hphisto/main/public/assets/icon-192.png
    ports:
      - target: 2346
        published: "2346"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/AppData/hphisto/data
        target: /data
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: clevim
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/clevim/hphisto/main/public/assets/icon-192.png
  index: /
  is_uncontrolled: false
  port_map: "2346"
  scheme: http
  store_app_id: hphisto
  title:
    custom: ""
    en_us: HΦSTO
